config/routes.rb
Rails.application.routes.draw do

  match '/signin', to: 'sessions#new', via: :get
  match '/sessions', to: 'sessions#create', via: :post
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/relationships/followers/count', to: 'relationships#refresh_followers', via: :get

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end
  match '/signup', to: 'users#new', via: :get

  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about', via: :get, as: :about
  match '/help', to: 'static_pages#help', via: :get, as: :help
  match '/contact', to: 'static_pages#contact', via: :get, as: :contact

  match '/map', to: 'static_pages#map', via: :get

end

app/views/shared/_error_messages.html.erb
<% if(object.errors.any?)  %>
    <div id="error_messages">
      <div class="alert alert-error">
        The form contains: <%= pluralize(object.errors.count, 'error') %>
      </div>
        <ul class="alert alert-error">
          <% object.errors.full_messages.each do |e| %>
            <li>* <%= e %> </li>
          <% end  %>
        </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <div id="feed">
      <h3>Tours  Feed</h3>
      <%= will_paginate @feed_items %>
        <ol class="microposts">
          <% @feed_items.all.each do |feed_item| %>
              <%= render 'shared/feed_item', feed_item: feed_item %>
          <% end  %>
        </ol>
      <%= will_paginate @feed_items %>
    </div>
<% end %>

app/views/shared/_feed_item.html.erb
<!--feed item has same name as partial. its done by rails automatically-->
<li id="<%= feed_item.id %>">
  <div class="panel panel-default">
    <aside id="feed_img">
        <% if !feed_item.image.nil?  %>
            <%= link_to(image_tag(feed_item.image, height: 82, width: 82, class: 'gravatar'), feed_item.user) %>
        <% else  %>
            <%= link_to gravatar_for(feed_item.user), feed_item.user %>
        <% end  %>
    </aside>
    <div class="panel-heading">
      <h4 class="panel-title"><%= feed_item.name %></h4>
    </div>
    <div class="panel-body">
      <%= feed_item.content %>
    </div>
    <span class="timestamp">
        posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
    <span class="user">
      posted by: <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <% if current_user?(feed_item.user) %>
        <%= link_to 'delete', feed_item, method: :delete,
                    confirm: 'Are you sure?',
                    title: feed_item.content %>
    <% end %>
  </div>
</li>

app/views/shared/_post_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: @micropost %>
    <div class="field">
      <%= f.text_field :name, placeholder: 'name' %>
    </div>
    <div class="field">
      <%= f.text_field :tour_type, placeholder: 'choose tour type' %>
    </div>
    <div class="field">
      <%= f.text_area :content, placeholder: 'description' %>
    </div>
    <div class="field">
      <%= f.text_area :kml, placeholder: 'kml', id: 'kmlString' %>
    </div>
    <div class="field">
      <label class="field" for="file">Upload tour image</label> <%= f.file_field :image, class: 'upload' %>
    </div>
    <%= f.submit 'Post', class: 'btn btn-large btn-primary'  %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div id="user_stats" class="stats" data-id = <%= @user.id %>>
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count  %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count  %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1><%= current_user.name %></h1>
<span><%= link_to 'view profile', current_user %></span>
<span><%= pluralize(current_user.microposts.count, 'post' )%></span>