config/routes.rb
Rails.application.routes.draw do

  match '/signin', to: 'sessions#new', via: :get
  match '/sessions', to: 'sessions#create', via: :post
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/relationships/followers/count', to: 'relationships#refresh_followers', via: :get

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end
  match '/signup', to: 'users#new', via: :get

  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about', via: :get, as: :about
  match '/help', to: 'static_pages#help', via: :get, as: :help
  match '/contact', to: 'static_pages#contact', via: :get, as: :contact

  match '/map', to: 'static_pages#map', via: :get

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <% if !signed_in? %>

    <div class="center" id="tst">
      <%= link_to 'Sign Up now!', signup_path, class: 'btn btn-large btn-info', id: 'signup' %>
    </div>
  <% end  %>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'pathway', root_path, id: 'logo' %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Help', help_path  %></li>
          <% if signed_in? %>
              <li><%= link_to('Users', users_path) %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to('Profile', user_path(current_user)) %></li>
                  <li><%= link_to('Settings', edit_user_path(current_user)) %> </li>
                  <li class="divider"></li>
                  <li><%= link_to('Sign Out', signout_path, method: 'delete') %> </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to 'Sign In', signin_path %></li>
          <% end  %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if ls 9]
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <script src="//maps.googleapis.com/maps/api/js?sensor=false&libraries=drawing" type="text/javascript"></script>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
          <% flash.each do |key, value| %>
              <%= content_tag(:div, value, class: "alert alert-#{key}") %>
          <% end %>
          <%= yield %>
          <%= render 'layouts/footer' %>
        </div>
    </body>
</html>